train_dir: data/train
val_dir: data/train

raw_data_columns:
  - user_id: string
  - create_time: string
  - log_type: string
  - watchlists: string
  - holdings: string
  - country: string
  - prefer_bid: string
  - user_propernoun: string
  - push_title: string
  - push_content: string
  - item_code: string
  - item_tags: string
  - submit_type: string

label_columns:
  - log_type
