train_dir: data/train
val_dir: data/train

# CSV格式设置（本地环境）
csv_format:
  separator: ","  # 本地环境使用逗号分隔符
  header: 0       # 本地环境有表头(0表示第一行是表头)
  # 线上环境请修改为：
  # separator: "\t"  # 制表符分隔
  # header: null     # 无表头

TXT格式设置（线上环境）
txt_format:
  separator: "\t"  # 制表符分隔
  header: null     # 无表头
  encoding: "utf-8"
  file_extension: ".txt"

raw_data_columns:
  - user_id: string
  - create_time: string
  - log_type: string
  - watchlists: string
  - holdings: string
  - country: string
  - prefer_bid: string
  - user_propernoun: string
  - push_title: string
  - push_content: string
  - item_code: string
  - item_tags: string
  - submit_type: string

label_columns:
  - log_type
