# 特征重要性评估配置
feature_importance_config:
  # 评估数据量配置
  eval_batches: 50          # 用于评估的批次数量 (默认50, 原来是5)
  max_eval_samples: 12800   # 最大评估样本数 (50 * 256 = 12,800)
  
  # 重复次数配置  
  importance_repeats: 10    # 排列重要性重复次数 (默认10, 原来是3)
  
  # 统计显著性配置
  significance_threshold: 0.01    # 重要性显著性阈值 (1%)
  confidence_level: 0.95          # 置信区间水平 (95%)
  
  # 输出配置
  save_detailed_results: true     # 是否保存详细结果
  include_statistics: true        # 是否包含统计信息
  plot_top_features: 20          # 图表显示的特征数量
  
  # 性能配置
  enable_parallel: false         # 是否启用并行评估 (暂不支持)
  memory_efficient: true         # 是否使用内存优化模式
  
# 评估质量配置
quality_settings:
  min_samples: 5000             # 最小样本数要求
  min_repeats: 5                # 最小重复次数要求
  max_std_ratio: 0.5            # 最大标准差/均值比率 (用于检测评估稳定性)
  
# 特征过滤配置
feature_filtering:
  min_importance: 0.0001        # 最小重要性阈值 (过滤微弱特征)
  exclude_patterns:             # 排除的特征名称模式
    - "temp_"
    - "_debug"
  
# 报告配置  
reporting:
  verbose: true                 # 是否显示详细信息
  show_confidence_intervals: true  # 是否显示置信区间
  show_significance_tests: true    # 是否显示显著性检验结果
  export_formats:               # 导出格式
    - "json"
    - "csv" 