ml_model_dir: "checkpoint/model.pth"
ml_model_hdfs_dir: "dongshaojie/ainvest_push/tree_model"
dowload_start_hour: 3
dowload_start_minute: 0
user_data_dir: data/user
new_user_data_dir: data/new_user
hour_task_minute: 35 # 每小时的35分执行下载任务
user_data_file_num: 5
max_user_num_per_iter: 20000
user_data_sql_dir: data/user.sql
new_user_data_sql_dir: data/new_user.sql  # 当天的新用户
user_data_save_days: 5 # 保留的数据文件数量，近N天
download_max_try: 3
sep: '\t'
header: null
data_index: user_id
data_columns:
  - user_id
  - watchlists
  - holdings
  - country
  - prefer_bid
varlen_max_col_num: 5
push_server_url: http://aime-recsys-push-server-prod:10010/aime/recsys/api/push/v2
push_server_url_v3: http://aime-recsys-push-server-prod:10010/aime/recsys/api/push/v3