boosting_type: "gbdt"
num_leaves: 31
max_depth: 5
learning_rate: 0.01
metric: "auc"
objective: "binary"
feature_fraction: 0.9
num_iterations: 300
early_stopping_rounds: 50
subsample: 0.8
colsample_bytree: 0.8
