from typing import Callable, Dict

from .common_operations import (
    astype,
    fillna,
    get_hour,
    json_to_list,
    list_get,
    list_get_join,
    list_hash,
    list_len,
    map_to_int,
    padding,
    scale,
    seperation,
    split,
    str_hash,
    to_bucket,
    to_date,
    weekday,
)
from .interaction_operations import intersection, intersection_num, is_in, union

OP_HUB: Dict[str, Callable] = {
    "fillna": fillna,
    "list_get": list_get,
    "list_hash": list_hash,
    "map_to_int": map_to_int,
    "padding": padding,
    "seperation": seperation,
    "split": split,
    "str_hash": str_hash,
    "scale": scale,
    "is_in": is_in,
    "astype": astype,
    "list_len": list_len,
    "to_bucket": to_bucket,
    "intersection": intersection,
    "to_date": to_date,
    "weekday": weekday,
    "get_hour": get_hour,
    "json_to_list": json_to_list,
    "union": union,
    "list_get_join": list_get_join,
    "intersection_num": intersection_num,
}
